In [7]:

# noms_abreges = ['CDS_Amadou', 'ISGTR_MamadouLamine', 'ISCL_Safietou', 'ISCL_NdeyeMarie', 'ISCL_NdeyeMarie']

#     # Effectuer la requête pour récupérer les emails correspondants
#     emails = NomTable.query.filter(NomTable.nom_abrege.in_(noms_abreges)).all()

In [8]:
import os
import random
import pandas as pd

random.randint(2,6)

3

In [9]:
random.getrandbits(14)

7301

In [10]:
import smtplib

In [11]:
server = smtplib.SMTP_SSL('smtp.gmail.com',465)


In [12]:
df=pd.read_excel('uploads/ECHANT_CTR_2023-05.xlsx').head(3)

In [13]:
for index, row in df.iterrows():
    print(pd.notnull(row['Date de résolution maximum']) or isinstance(row['Date de résolution maximum'], pd.Timestamp))

True
True
True


In [14]:
os.path.join(os.getcwd(),'files_rejet')

'/home/dev/desc_gmec/files_rejet'

In [15]:
import os
import glob
import pandas as pd

folder_path = os.path.join(os.getcwd(), 'files_rejet')

# Obtenir la liste des fichiers dans le répertoire triés par date de modification
file_list = glob.glob(os.path.join(folder_path, 'rejected_records_*.csv'))
file_list.sort(key=os.path.getmtime)

# Sélectionner le dernier fichier dans la liste
latest_file = file_list[-1]

# Charger le fichier avec pandas pour le traitement
df = pd.read_csv(latest_file)

print(df['XX_AGENT_RESPONSABLE'].head())


0             CDS_Amadou
1    ISGTR_MamadouLamine
2        ISCL_NdeyeMarie
3        ISCL_NdeyeMarie
4              CDS_Seyni
Name: XX_AGENT_RESPONSABLE, dtype: object


In [16]:
data = pd.read_csv(latest_file)
noms_abreges = data['XX_AGENT_RESPONSABLE'].tolist()


In [17]:
noms_abreges = list(set(noms_abreges))
noms_abreges

['CDS_Safietou',
 'CDS_Raqui',
 'ISGTR_PapaDemba',
 'CDS_Dieynaba',
 'ISCC_Aminata',
 'CDS_Seyni',
 'ISCL_NdeyeMarie',
 'CDS_MarieRosine',
 'ISCL_Ibrahima',
 'ISDC_Sadibou',
 'ISFAC_Talibouya',
 'ISCL_Eleonore',
 'CDS_Herve',
 'ISDC_MamadouLamine',
 'ISFAC_Chems',
 'CDS_Fernande',
 'ISREC_Sira',
 'CDS_Amadou',
 'ISCL_MameAwa',
 'ISGTR_MamadouLamine',
 'ISGRC_Alassane',
 'ISCL_Maty']

In [18]:
['CDS_MarieRosine','CDS_Seyni','ISGRC_Alassane','ISFAC_Talibouya','ISGTR_MamadouLamine','ISDC_Sadibou','ISCL_Maty','CDS_Amadou','ISCL_Safietou','CDS_Raqui','CDS_Fernande','CDS_Herve','ISCL_MameAwa','CDS_Safietou','ISFAC_Chems','ISCL_Ibrahima','CDS_Dieynaba','ISREC_Ababacar','ISCL_NdeyeMarie','ISCC_Aminata','ISDC_MamadouLamine']

['CDS_MarieRosine',
 'CDS_Seyni',
 'ISGRC_Alassane',
 'ISFAC_Talibouya',
 'ISGTR_MamadouLamine',
 'ISDC_Sadibou',
 'ISCL_Maty',
 'CDS_Amadou',
 'ISCL_Safietou',
 'CDS_Raqui',
 'CDS_Fernande',
 'CDS_Herve',
 'ISCL_MameAwa',
 'CDS_Safietou',
 'ISFAC_Chems',
 'ISCL_Ibrahima',
 'CDS_Dieynaba',
 'ISREC_Ababacar',
 'ISCL_NdeyeMarie',
 'ISCC_Aminata',
 'ISDC_MamadouLamine']

In [19]:
['safietou.ndiaye@sonatel-orange.com'][0].split('@')[0].split('.')[0]

'safietou'

In [20]:
import numpy as np

def actLU(A):
    n = A.shape[0]
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    for i in range(n):
        # Calcul de la matrice U
        for k in range(i, n):
            sum_ = 0
            for j in range(i):
                sum_ += L[i][j] * U[j][k]
            U[i][k] = A[i][k] - sum_

        # Calcul de la matrice L
        for k in range(i, n):
            if i == k:
                L[i][i] = 1
            else:
                sum_ = 0
                for j in range(i):
                    sum_ += L[k][j] * U[j][i]
                L[k][i] = (A[k][i] - sum_) / U[i][i]

    return L, U

# Matrice d'exemple
A = np.array([[3, 1, 2], [3, 2, 6], [6, 1, -1]])

# Appel de la fonction actLU
L, U = actLU(A)

# Affichage des résultats
print("Matrice A :")
print(A)
print("\nMatrice L :")
print(L)
print("\nMatrice U :")
print(U)


Matrice A :
[[ 3  1  2]
 [ 3  2  6]
 [ 6  1 -1]]

Matrice L :
[[ 1.  0.  0.]
 [ 1.  1.  0.]
 [ 2. -1.  1.]]

Matrice U :
[[ 3.  1.  2.]
 [ 0.  1.  4.]
 [ 0.  0. -1.]]


In [21]:
import numpy as np

def sol2(U, b):
    n = U.shape[0]
    x = np.zeros(n)

    for i in range(n - 1, -1, -1):
        sum_ = 0
        for j in range(i + 1, n):
            sum_ += U[i][j] * x[j]
        x[i] = (b[i] - sum_) / U[i][i]

    return x

# Matrice U et vecteur b de l'exemple
U = np.array([[-1, 2, 3], [0, 5, 7], [0, 0, 5]])
b = np.array([4, 3, 1])

# Appel de la fonction sol2
x = sol2(U, b)

# Affichage du résultat
print("Solution x :")
print(x)


Solution x :
[-2.76  0.32  0.2 ]


### 5 matrice tridiagonale

In [ ]:
# 1. Montrer que la triangularisation revient `a poser :
def solve_tridiagonal_system(a, b, c, k):
    n = len(b)
    w = [0] * n
    y = [0] * n

    # Calcul des variables w et y
    w[0] = c[0] / b[0]
    y[0] = k[0] / b[0]

    for i in range(1, n):
        w[i] = c[i] / (b[i] - a[i] * w[i-1])
        y[i] = (k[i] - a[i] * y[i-1]) / (b[i] - a[i] * w[i-1])

    return w, y

# Exemple d'utilisation
a = [0, e2, ..., en]  # Les éléments diagonaux inférieurs
b = [a1, a2, ..., an]  # Les éléments diagonaux principaux
c = [c1, c2, ..., cn-1]  # Les éléments diagonaux supérieurs
k = [k1, k2, ..., kn]  # Les termes constants du système

w, y = solve_tridiagonal_system(a, b, c, k)

# Les tableaux w et y contiennent les valeurs correspondantes aux équations désirées.


Pour évaluer le nombre d'opérations nécessaires pour résoudre le système tridiagonal à l'aide de la méthode de Gauss, on peut compter le nombre total d'opérations effectuées dans l'algorithme.

Dans l'algorithme précédent, le nombre d'opérations principales est lié à la boucle for qui itère de 1 à n-1, ce qui représente n-1 itérations. À chaque itération, il y a quelques opérations de calcul, mais elles sont généralement de l'ordre de grandeur constant par rapport à n. Par conséquent, on peut approximer le nombre total d'opérations principales par (n-1).

In [ ]:
def solve_tridiagonal_system(a, b, c, k):
    n = len(b)
    w = [0] * n
    y = [0] * n

    w[0] = c[0] / b[0]
    y[0] = k[0] / b[0]

    for i in range(1, n):
        w[i] = c[i] / (b[i] - a[i] * w[i-1])
        y[i] = (k[i] - a[i] * y[i-1]) / (b[i] - a[i] * w[i-1])

    return w, y

# Exemple d'utilisation
a = [0, e2, ..., en]
b = [a1, a2, ..., an]
c = [c1, c2, ..., cn-1]
k = [k1, k2, ..., kn]

w, y = solve_tridiagonal_system(a, b, c, k)

# Les tableaux w et y contiennent les valeurs correspondantes aux équations désirées.


In [ ]:

import numpy as np

# Définition de la matrice C et du vecteur d
C = np.array([[3, 0, -1, 0],
              [2, 1, 1, 3],
              [0, 1, 0, -1],
              [0, 0, 0, 1]])

d = np.array([1, 1, 3, 4, 3, 5])

# Séparation du système en une sous-matrice 3x3 et une inconnue x4
A = C[:3, :3]
b = d[:3]

# Résolution pour l'inconnue x4
x4 = d[3] / C[3, 3]

# Résolution du système 3x3 restant
A[2, 2] -= C[2, 3] * C[3, 2] / C[3, 3]
b[2] -= C[2, 3] * d[3] / C[3, 3]

# Factorisation LU
L = np.eye(3)
U = np.zeros((3, 3))

for i in range(3):
    for j in range(i, 3):
        U[i, j] = A[i, j] - np.dot(L[i, :i], U[:i, j])
    for j in range(i + 1, 3):
        L[j, i] = (A[j, i] - np.dot(L[j, :i], U[:i, i])) / U[i, i]

# Résolution du système Ax = b
y = np.linalg.solve(L, b)
x = np.linalg.solve(U, y)

# Calcul de la matrice inverse A^-1 à partir de A = LU
A_inv = np.linalg.inv(A)

# Affichage des résultats
print("x4 =", x4)
print("Système 3x3 restant :")
print("A =")
print(A)
print("b =", b)
print("L =")
print(L)
print("U =")
print(U)
print("Solution x =", x)
print("Matrice inverse A^-1 :")
print(A_inv)


Ce script utilise la bibliothèque NumPy pour effectuer les opérations matricielles. Assurez-vous d'avoir NumPy installé pour l'exécuter.

Les commentaires dans le script expliquent les différentes étapes, y compris la séparation du système en une sous-matrice 3x3 et une inconnue, la résolution du système pour l'inconnue x4, la factorisation LU de la sous-matrice 3x3, la résolution du système restant et le calcul de la matrice inverse A^-1 à partir de la factorisation LU.

N'hésitez pas à me demander des éclaircissements supplémentaires si nécessaire.

In [ ]:
import numpy as np

# Définition de la matrice C et du vecteur d
C = np.array([[3, 0, -1, 0],
              [2, 1, 1, 3],
              [0, 1, 0, -1],
              [0, 0, 0, 1]])

d = np.array([1, 1, 3, 4, 3, 5])

# Séparation du système en une sous-matrice 3x3 et une inconnue x4
A = C[:3, :3]
b = d[:3]

# Résolution pour l'inconnue x4
x4 = d[3] / C[3, 3]

# Résolution du système 3x3 restant
A[2, 2] -= C[2, 3] * C[3, 2] / C[3, 3]
b[2] -= C[2, 3] * d[3] / C[3, 3]

# Résolution du système 3x3
x = np.linalg.solve(A, b)

# Affichage des résultats
print("Inconnue x4 =", x4)
print("Système 3x3 restant :")
print("A =")
print(A)
print("b =", b)
print("Solution x =", x)


Inconnue x4 = 4.0
Système 3x3 restant :
A =
[[ 3  0 -1]
 [ 2  1  1]
 [ 0  1  0]]
b = [1 1 7]
Solution x = [-1.  7. -4.]


### 1. La r´esolution de ce syst`eme peut ˆetre ramen´ee `a celle d?un syst`eme line?aire
### de dimension trois, l’inconnue x4 ´etant facile `a d´eterminer. Donner cette
### inconnue et le syst`eme 3 × 3 restant, que l’on notera Ax = b.
### proposer une solution

In [ ]:
import numpy as np

# Matrice A 3x3
A = np.array([[3, 0, -1],
              [2, 1, 1],
              [1, 1, -1]])

# Vecteur b
b = np.array([1, 1, 3])

# Résolution du système 3x3
x4 = 4  # Valeur de x4 trouvée précédemment
b = b - A[:, 2] * x4  # Mise à jour du vecteur b en enlevant l'effet de x4

# Méthode de substitution arrière
x = np.zeros(3)
n = len(x)

x[n-1] = b[n-1] / A[n-1, n-1]  # Calcul de la dernière inconnue

for i in range(n-2, -1, -1):
    x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]

# Affichage de la solution
print("Solution :")
for i in range(n):
    print(f"x{i+1} =", x[i])


Solution :
x1 = -0.6666666666666666
x2 = 4.0
x3 = -7.0


### 2. Factoriser la matrice A en produit LU (o`u L est triangulaire inf´erieure
### `a diagonale unit´e et U triangulaire sup´erieure) puis r´esoudre le syst`eme.
### D´eduire A−1 `a partir de A = LU.

In [ ]:
import numpy as np

# Matrice A 4x4
A = np.array([[3, 0, -1, 0],
              [2, 1, 1, 0],
              [1, 1, 0, -1],
              [0, 0, 0, 1]])

# Vecteur d
d = np.array([1, 1, 3, 4])

# Factorisation LU
P, L, U = scipy.linalg.lu(A)

# Résolution du système LUx = d
y = np.linalg.solve(L, P.dot(d))
x = np.linalg.solve(U, y)

# Calcul de A^(-1)
A_inv = np.linalg.inv(A)

# Affichage des résultats
print("Matrice L :")
print(L)
print("Matrice U :")
print(U)
print("Vecteur solution x :")
print(x)
print("Matrice inverse A^(-1) :")
print(A_inv)


Dans ce code, nous utilisons la fonction scipy.linalg.lu pour effectuer la factorisation LU de la matrice A. Cette fonction retourne trois matrices : P (matrice de permutation), L (matrice triangulaire inférieure unitaire) et U (matrice triangulaire supérieure). Ensuite, nous utilisons les fonctions numpy.linalg.solve pour résoudre les systèmes triangulaires inférieurs et supérieurs afin d'obtenir la solution x du système original.

Enfin, nous utilisons la fonction numpy.linalg.inv pour calculer l'inverse de la matrice A.

In [ ]:

def send_daily_reminder_email():
    # Calculate the date for the previous day
    previous_day = datetime.now() - timedelta(days=1)
    previous_day = previous_day.date()

    # Query the tickets that are pending and have a resolution date before the previous day
    pending_tickets = Ticket.query.filter(Ticket.statut_demande == 'Défaut (OUI/NON)',
                                          Ticket.date_resolution_max < previous_day).all()

    # Group the tickets by agent
    tickets_by_agent = {}
    for ticket in pending_tickets:
        if ticket.evaluateur in tickets_by_agent:
            tickets_by_agent[ticket.evaluateur].append(ticket)
        else:
            tickets_by_agent[ticket.evaluateur] = [ticket]

    # Send the reminder email to each agent with pending tasks
    for agent, tickets in tickets_by_agent.items():

        # Get agent information
        agent_info = User.query.filter(User.nom_abrege == agent).first()
        if agent_info:
            recipient = agent_info.email
            nom_abrege_agent = agent_info.nom_abrege
            login = agent_info.login
            nom = agent_info.nom

            subject = 'Rappel : Tâches en attente dans QUALITE'
            body = f"Bonjour {nom} {nom_abrege_agent}," \
                   f"\nVous avez des tâches en attente de traitement dans QUALITE. Merci de les prendre en charge." \
                   f"\n\nVoici la liste des tâches en attente :"

            for ticket in tickets:
                body += f"\n\n- Libellé de la tâche : {ticket.libelle_service}" \
                        f"\n  Action attendue : {ticket.description}" \
                        f"\n  Date d'imputation : {ticket.enregistre_le}" \
                        f"\n  Date du jour : {previous_day}" \
                        f"\n  Délai écoulé : {previous_day - ticket.enregistre_le}"

            body += "\n\nCordialement,\nL'équipe QUALITE"

            msg = Message(subject, sender=app.config['MAIL_USERNAME'], recipients=["diopabubakr79@gmail.com"])
            msg.body = body
            mail.send(msg)

            # Send a copy to the chef de service or chef de département
            if agent_info.role.role == 'Agent':
                chef_service = User.query.filter(User.service.nom == agent_info.service.nom, User.role.role == 'Chef de Service').first()
                if chef_service:
                    msg_cc = Message(subject, sender=app.config['MAIL_USERNAME'], recipients=['compte14031970@gmail.com'])
                    msg_cc.body = body
                    mail.send(msg_cc)

            elif agent_info.role.role == 'Chef de Service':
                chef_departement = User.query.filter(User.departement == agent_info.departement, User.role == 'Chef de département').first()
                if chef_departement:
                    msg_cc = Message(subject, sender=app.config['MAIL_USERNAME'], recipients=['diopb4826@gmail.com'])
                    msg_cc.body = body
                    mail.send(msg_cc)

In [24]:
m = 1

if m ==2 :
    print("Trouvé")
elif m == 1:
    print('Presque')
else :
    print('Fauché')

Presque


In [33]:
m= 10

while m:
    print(m)
    if m==4:
        print("Vous êtes presque arrivé")
    m-=1


10
9
8
7
6
5
4
Vous êtes presque arrivé
3
2
1
